### ISSUE TITLE
Error in saving the codebook into video file 

### ISSUE THREAD

**Issue by siang13** [bkakilli/Codebook#1]
The output file is not readable with the error of missing header. Can you please check it out and provide solution for that?Thanks

**Comment by bkakilli** [comment]
Hi siang. Sorry I did not clearly understand your problem. Can you tell me where you get the error, during training or during background substraction? Also please provide a screenshot of the error, your video file and the trained codebook file (if you have).

**Comment by siang13** [comment]
Hi Burak Kakillioğlu,glad to get your reply.Below are the attachment of the
screenshot and video.I have make some modification for easier the testing
purpose as i am running this program with visual studio 2013 and opencv 3.0.

On Mon, Jul 25, 2016 at 5:11 AM, Burak Kakillioğlu <notifications@github.com

**Comment by siang13** [comment]
Firstly i test with trainning the mp4 video file , then i try to play the
video file that u save with the coding, i can't play the file because of
the file header is missing in the saved video file. Please help me to solve
it.Thanks

**Comment by bkakilli** [comment]
Sorry for the late response. I did not have computer access last month. I'll try to answer for future reference.
The error you mention is not from this code. It is probably coming from the video player in OpenCV. So as I understood, you are trying to provide the output codebook file (which I call as 'cbf' file) as the video file in subtraction. This project does not create or save a new video (neither in training nor in subtraction). Instead, it creates and saves only the "codebook" which is proposed in the paper I referred. When you want to subtract the background (or play the video without background) you need to **provide the codebook file**, that you generated during training, **together with the video file**. If you provide a video that is not compatible with the codebook file you provided (different resolution than the video), you get an error.
